import Head from "next/head";
import { Separator } from "~/components/ui/separator";
import { AddRepoForm } from "~/containers/repositories/AddRepo";

export default function Home() {
  return (
    <>
      <Head>
        <title>Combat Training</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-6">
        <div>
          <h3 className="text-lg font-medium">Add a Repository</h3>
          <p className="text-sm text-muted-foreground">
            Select a repository to add to your Combat Training.
          </p>
        </div>
        <Separator />
        <AddRepoForm />
      </div>
    </>
  );
}
