import { type File } from "@prisma/client";
import Head from "next/head";
import { useParams } from "next/navigation";
import { Separator } from "~/components/ui/separator";
import { Skeleton } from "~/components/ui/skeleton";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "~/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "~/components/ui/tabs";
import { api } from "~/utils/api";

function FileTable({ files }: { files: File[] }) {
  return (
    <Table>
      <TableHeader>
        <TableRow>
          <TableHead className="w-[100px]">URL</TableHead>
          <TableCell className="text-right"></TableCell>
        </TableRow>
      </TableHeader>
      <TableBody>
        {files.map((file) => (
          <TableRow key={file.id}>
            <TableCell className="font-medium">{file.url}</TableCell>
            <TableCell className="text-right"></TableCell>
          </TableRow>
        ))}
      </TableBody>
    </Table>
  );
}

export default function Home() {
  const { repoId } = useParams<{ repoId: string }>();
  const { data: files, isLoading } = api.repo.getFiles.useQuery({
    repoId: parseInt(repoId),
  });
  return (
    <>
      <Head>
        <title>Combat Training</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="space-y-6">
        <Tabs defaultValue="my-repos">
          <TabsList>
            <TabsTrigger value="my-repos">
              Files
              <span className="ml-2 text-sm text-muted-foreground">
                {files?.length}
              </span>
            </TabsTrigger>
            <TabsTrigger value="add">Actions</TabsTrigger>
          </TabsList>
          <TabsContent value="my-repos">
            <div className="px-4">
              {isLoading && <Skeleton className="h-20" />}
              {files && <FileTable files={files} />}
            </div>
          </TabsContent>
          <TabsContent value="add">
            <div className="px-4">
              <h3 className="text-lg font-medium">Actions</h3>
              <p className="text-sm text-muted-foreground">
                Helper actions for your repositories
              </p>
            </div>
            <Separator />
          </TabsContent>
        </Tabs>
      </div>
    </>
  );
}
